export const CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION';
export const TOGGLE_SUBSCRIPTION = 'TOGGLE_SUBSCRIPTION';
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SUBSCRIBE = 'SUBSCRIBE';
export const FIND_SUBSCRIPTION = 'FIND_SUBSCRIPTION';
export const CHECK_SUBSCRIPTION = 'CHECK_SUBSCRIPTION';
export const SUBMIT_POLL_FORM = 'SUBMIT_POLL_FORM';
export const SUBMIT_USERPAGE_FORM = 'SUBMIT_USERPAGE_FORM';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';

export const GET_USERS_ARRAY = 'GET_USERS_ARRAY';
