export const CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION';
export const TOGGLE_SUBSCRIPTION = 'TOGGLE_SUBSCRIPTION';
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SUBSCRIBE = 'SUBSCRIBE';
export const FIND_SUBSCRIPTION = 'FIND_SUBSCRIPTION';
export const CHECK_SUBSCRIPTION = 'CHECK_SUBSCRIPTION';
