//SERVICE WORKER
export const SERVICE_WORKER_REGISTRATION = 'SERVICE_WORKER_REGISTRATION';
export const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
export const ENABLE_NOTIFICATION = 'ENABLE_NOTIFICATION';
export const DISABLE_BUTTON = 'DISABLE_BUTTON';
export const SET_NOTIFICATION_SUPPORT = 'SET_NOTIFICATION_SUPPORT';
export const CONNECTION_UNSTABLE = 'CONNECTION_UNSTABLE';
//FORM MANAGEMENT
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_ARRAY_FIELD = 'UPDATE_ARRAY_FIELD';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const CLEAR_STATE = 'CLEAR_STATE';
export const ADD_OPTION = 'ADD_OPTION';
export const INSERT_PICTURES = 'INSERT_PICTURES';
export const SET_CATEGORY_NAME = 'SET_CATEGORY_NAME';
export const SET_DATE_TIME = 'SET_DATE_TIME';
export const UPDATE_ERROR_FIELD = 'UPDATE_ERROR_FIELD';
export const CLEAR_FORM = 'CLEAR_FORM';
export const SET_INITIAL_FORM = 'SET_INITIAL_FORM';
export const SET_TIME_LIMIT = 'SET_TIME_LIMIT';
export const CHANGE_MUTABLE_STATE = 'CHANGE_MUTABLE_STATE';
export const UPDATE_ARRAY_PICTURES = 'UPDATE_ARRAY_PICTURES';
export const ADD_SUBJECT_PICTURE = 'ADD_SUBJECT_PICTURE';
export const DELETE_OPTION = 'DELETE_OPTION';
export const CLEAR_PICTURE = 'CLEAR_PICTURE';

//USERS ARRAY
export const SET_USERS_ARRAY = 'SET_USERS_ARRAY';
