
export const SERVICE_WORKER_REGISTRATION = 'SERVICE_WORKER_REGISTRATION';
export const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
export const ENABLE_NOTIFICATION = 'ENABLE_NOTIFICATION';
export const DISABLE_BUTTON = 'DISABLE_BUTTON';
export const SET_NOTIFICATION_SUPPORT = 'SET_NOTIFICATION_SUPPORT';

